name: Build JSL

on: ["push", "pull_request"]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        # should this use macos-latest?
        os: [ubuntu-latest, macos-11, windows-latest]
    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install dependencies (Linux)
        if: runner.os == 'Linux'
        run: sudo apt install libhidapi-dev

      - name: Build (Windows)
        if: runner.os == 'Windows'
        run: |
          cmake -B build -DBUILD_SHARED_LIBS=TRUE
          cmake --build build --config Release

      - name: Build (macOS)
        if: runner.os == 'macOS'
        run: |
          cmake -B build -DCMAKE_OSX_ARCHITECTURES=arm64;x86_64 -DBUILD_SHARED_LIBS=ON
          cmake --build build

      - name: Build (Linux)
        if: runner.os == 'Linux'
        run: |
          cmake -B build -DBUILD_SHARED_LIBS=TRUE
          cmake --build build
      
      - name: Upload artifact (Windows)
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v3
        with:
          name: JSL-${{ runner.os }}
          path: build/JoyShockLibrary/Release/JoyShockLibrary.dll

      - name: Upload artifact (macOS)
        if: runner.os == 'macOS'
        uses: actions/upload-artifact@v3
        with:
          name: JSL-${{ runner.os }}
          path: build/JoyShockLibrary/libJoyShockLibrary.dylib

      - name: Upload artifact (Linux)
        if: runner.os == 'Linux'
        uses: actions/upload-artifact@v3
        with:
          name: JSL-${{ runner.os }}
          path: build/JoyShockLibrary/libJoyShockLibrary.so
